[project]
name = "update-readme-version"
version = "0.1.0"
description = ""
authors = [{ name = "Peter Borocz", email = "680893+PBorocz@users.noreply.github.com" }]
requires-python = ">=3.11,<3.13"
dependencies = [
    "pyinstaller>=6.3.0,<7",
    "yachalk>=0.1.5,<0.2",
]

[dependency-groups]
dev = ["pytest>=9.0.0,<10.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poe]
verbosity = 2

[tool.poe.tasks]
BUILD = ["_clean", "_build"]
INSTALL = "cp -R dist/update_readme_version/* /Users/peter/.local/bin/"

_build = "pyinstaller --onedir update_readme_version.py"
_clean	= "rm -rf dist build"
